# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: starter-blog
day_night: true
font: 'native'
font_size: L

# SEO

site_type: Person
local_business_type: ''
org_name: ''
description: 'Luis Gabriel Gomez personal site. Software architect and developer.'
twitter: ''

# Site header

main_menu:
  enable: true
  align: c
  show_logo: false
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: false

# Localization

date_format: 'Jan 2, 2006'
time_format: '15:04 MST'

# Site features

highlight: true
highlight_languages:
  - r
  - c
  - cpp
  - csharp
  - bash
  - arduino
  - go
  - python
  - vhdl
  - yaml
math: true
diagram: true
privacy_pack: false
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    post: false
show_related:
  post: true
email: hello.luisgg@protonmail.com
sharing_image: ''
reading_time: true
section_pager: true
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
plugins_js: []
avatar:
  gravatar: false
  shape: circle
comments:
  provider: ''
  commentable:
    post: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: ''
  api_key: ''
  zoom: 15
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
cms:
  branch: main
  local_backend: false
  netlify_cms: false
icon:
  pack:
    ai: false
